apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mynginx.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
  - http:
      paths:
      - path: /test
        pathType: Prefix
        backend:
          service:
            name: {{ include "mynginx.fullname" . }}
            port:
              number: 80
  ingressClassName: public